#pragma once

#define TUNE_PARAMETER(name) \
    int name;               \
    int name##_min;         \
    int name##_max;         \
    int name##_step;

struct Options {
    int Threads;

    TUNE_PARAMETER(RFP_MARGIN)
    TUNE_PARAMETER(NMP_REDUCTION_EVAL_DIVISOR)
    TUNE_PARAMETER(RAZORING_COEFF_0)
    TUNE_PARAMETER(DOUBLE_EXTENSION_MARGIN)
    TUNE_PARAMETER(HISTORY_QUIET_LMR_DIVISOR)
    TUNE_PARAMETER(HISTORY_NOISY_LMR_DIVISOR)
    TUNE_PARAMETER(DO_DEEPER_BASE_MARGIN)
    TUNE_PARAMETER(QS_FUTILITY)
    // part 2
    TUNE_PARAMETER(HISTORY_BONUS_MAX)
    TUNE_PARAMETER(LMR_QUIET_BASE)
    TUNE_PARAMETER(LMR_QUIET_DIVISOR)
    TUNE_PARAMETER(LMR_NOISY_BASE)
    TUNE_PARAMETER(LMR_NOISY_DIVISOR)
    // part 3
    TUNE_PARAMETER(SEE_QUIET_MARGIN)
    TUNE_PARAMETER(SEE_NOISY_MARGIN)
    // part 4
    TUNE_PARAMETER(FUTILITY_COEFF_0)
    TUNE_PARAMETER(FUTILITY_COEFF_1)
    // part 5
    TUNE_PARAMETER(LMR_DEPTH_HISTORY_DIVISOR)
    TUNE_PARAMETER(DELTA_RESIZE)
    // part 6
    TUNE_PARAMETER(HISTORY_MALUS_MAX)
    TUNE_PARAMETER(HISTORY_BONUS_OFFSET)
    TUNE_PARAMETER(HISTORY_MALUS_OFFSET)
    // part 7
    TUNE_PARAMETER(NODE_TM_SUBTREE_MULTIPLIER)


};

extern struct Options options;
